// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEUvP9K0RGQiDOxdCpTvbjJrFKvYJ2btk',
    appId: '1:1032203695512:web:1eb46966be6153e79be7ed',
    messagingSenderId: '1032203695512',
    projectId: 'snapfolio-8d760',
    authDomain: 'snapfolio-8d760.firebaseapp.com',
    storageBucket: 'snapfolio-8d760.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjeFUvNVjBBQ0oOR0g-6xgkdD3PmM-RWQ',
    appId: '1:1032203695512:android:9c4dc0360cacdb639be7ed',
    messagingSenderId: '1032203695512',
    projectId: 'snapfolio-8d760',
    storageBucket: 'snapfolio-8d760.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxWvA3gNL1Nlh4e_ql0cCqspHKeQc2bfs',
    appId: '1:1032203695512:ios:6f7ca215a023ec7b9be7ed',
    messagingSenderId: '1032203695512',
    projectId: 'snapfolio-8d760',
    storageBucket: 'snapfolio-8d760.firebasestorage.app',
    iosBundleId: 'com.ricky.snapfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxWvA3gNL1Nlh4e_ql0cCqspHKeQc2bfs',
    appId: '1:1032203695512:ios:6f7ca215a023ec7b9be7ed',
    messagingSenderId: '1032203695512',
    projectId: 'snapfolio-8d760',
    storageBucket: 'snapfolio-8d760.firebasestorage.app',
    iosBundleId: 'com.ricky.snapfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEUvP9K0RGQiDOxdCpTvbjJrFKvYJ2btk',
    appId: '1:1032203695512:web:203e6cd9a48d52229be7ed',
    messagingSenderId: '1032203695512',
    projectId: 'snapfolio-8d760',
    authDomain: 'snapfolio-8d760.firebaseapp.com',
    storageBucket: 'snapfolio-8d760.firebasestorage.app',
  );
}
